/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file           : main.c
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "usart.h"
#include "gpio.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
/* Phase 2 peripherals: CubeMX no longer emits their init calls. */
#include "rtc.h"
#include "crc.h"
#include "fmc.h"
#include "usb_device.h"
#include "lwip.h"

#include "relay.h"
#include "IAP_server.h"
#include "IAP_boot_handoff.h"
#include "iap_auth.h"
#include "owner_slot.h"

/* Board bring-up tests, v0.1.3-testcase branch. Set one of these to 1 to boot
 * straight into it instead of the bootloader; each *_Test_Run never returns, so
 * only one may be enabled at a time. */

/* STKNX bring-up: TP1 bit timing is generated by the MCU itself. Receive-only
 * by default, see KNX_TX_ENABLE in knx_test.c. */
#ifndef KNX_TEST_ENABLE
#define KNX_TEST_ENABLE 0
#endif
#if KNX_TEST_ENABLE
#include "KNX/knx_test.h"
#endif

/* The phase cycle: P0 report, P1/P2 loopback, P3 listen, P4 normal. */
#ifndef CAN_TEST_ENABLE
#define CAN_TEST_ENABLE 0
#endif

/* One normal-mode session that never changes phase: transmit on an interval,
 * print every frame received, recover from bus-off. Transmitting can be turned
 * off with CAN_SOAK_TX_ENABLE in can_test.c. */
#ifndef CAN_SOAK_TEST_ENABLE
#define CAN_SOAK_TEST_ENABLE 0
#endif

/* Three steps on a loop for an oscilloscope on PB9: GPIO square wave, then
 * loopback frames back to back, then normal-mode frames back to back. */
#ifndef CAN_SCOPE_TEST_ENABLE
#define CAN_SCOPE_TEST_ENABLE 0
#endif

/* Reply to every frame with its payload incremented by one, same identifier.
 * Transmits nothing on its own. Host side: $TOOL/TestCase/tools/can_send.py */
#ifndef CAN_ECHO_TEST_ENABLE
#define CAN_ECHO_TEST_ENABLE 0
#endif

#if CAN_TEST_ENABLE || CAN_SOAK_TEST_ENABLE || CAN_SCOPE_TEST_ENABLE || CAN_ECHO_TEST_ENABLE
#include "CAN/can_test.h"
#endif

/* RS485 on USART2 through the SP3485EN: pin-level check, a periodic banner,
 * and an echo of whatever arrives. Host side: $TOOL/TestCase/tools/rs485_echo.py */
#ifndef RS485_TEST_ENABLE
#define RS485_TEST_ENABLE 0
#endif
#if RS485_TEST_ENABLE
#include "RS485/rs485_test.h"
#endif

/* Board bring-up cases 1, 2, 3, 4 and 11 together in one flash. They share no
 * pin and no peripheral instance except ADC1, which one file owns - the
 * reasoning is in TestCase/common/bringup_test.h. */
#ifndef BRINGUP_TEST_ENABLE
#define BRINGUP_TEST_ENABLE 0
#endif
#if BRINGUP_TEST_ENABLE
#include "bringup_test.h"
#endif

#if (KNX_TEST_ENABLE + CAN_TEST_ENABLE + CAN_SOAK_TEST_ENABLE \
     + CAN_SCOPE_TEST_ENABLE + CAN_ECHO_TEST_ENABLE + RS485_TEST_ENABLE + BRINGUP_TEST_ENABLE) > 1
#error "Only one bring-up test can run: none of them return. Pick one."
#endif
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
#ifdef __GNUC__
#define PUTCHAR_PROTOTYPE int __io_putchar(int ch)
#else
#define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
#endif /* __GNUC__ */
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MPU_Config(void);
/* USER CODE BEGIN PFP */

/* Bounded stand-in for ITM_SendChar(): never spin forever on the trace FIFO. */
static void itm_putchar_bounded(uint8_t ch)
{
	if (((ITM->TCR & ITM_TCR_ITMENA_Msk) == 0UL) || ((ITM->TER & 1UL) == 0UL)) {
		return;
	}
	for (uint32_t spins = 0U; spins < 1000U; spins++) {
		if (ITM->PORT[0U].u32 != 0UL) {
			ITM->PORT[0U].u8 = ch;
			return;
		}
	}
}

/* stdout goes to SWO/ITM and RS232, both bounded: a bootloader must never hang
 * on a log line. */
PUTCHAR_PROTOTYPE {
	itm_putchar_bounded((uint8_t) ch);
	(void) HAL_UART_Transmit(&huart4, (uint8_t*) &ch, 1, 10);
	return ch;
}
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* What server_decide() settled on. Phase 2 and the superloop key off it. */
static IAP_Method s_boot_mode = IAP_NONE;

/* Startup window: the relay clicks are the operator's cue to press BOOT0.
 * 3 relays x 500 ms = 1.5 s, then one read.
 *
 * ⚠️ The judgement is "was the button down at the 1.5 s mark", NOT "was it
 * held for 1.5 s". BOOT0 is not looked at while the relays click. Holding the
 * button throughout is just the practical way to be sure of covering that one
 * instant, which is what the banner is really telling the operator to do. */
#define BOOT0_WINDOW_MS        500U
#define BOOT0_WINDOW_RELAYS    3U

/* Keep holding past the decision point and it becomes a second gesture:
 * factory reset (requirement C10). Ten seconds is far enough from
 * the 1.5 s mark that nobody reaches it by holding "a bit longer to be sure". */
#define BOOT0_FACTORY_HOLD_MS  10000U

/* A button that never reads as released is a stuck button or a shorted net.
 * Waiting for it forever would leave the board sitting in this loop with no
 * output and no way on, which looks exactly like a dead bootloader. */
#define BOOT0_HOLD_LIMIT_MS    30000U

#define BOOT0_POLL_MS          10U

typedef enum {
	BOOT0_GESTURE_NONE = 0,       /* not down at the decision point            */
	BOOT0_GESTURE_UPLOAD,         /* down at 1.5 s, released before 10 s       */
	BOOT0_GESTURE_FACTORY_RESET   /* held past 10 s, then released             */
} boot0_gesture_t;

/*
 * Three fast clicks: "the factory-reset gesture is armed, let go now".
 *
 * Audible rather than visual on purpose. This board has no general-purpose
 * LED, and it is usually inside a cabinet where nobody can see one anyway --
 * the relay clicks are already how the startup window announces itself.
 */
static void boot0_armed_signal(void)
{
	for (uint32_t i = 0U; i < 3U; i++) {
		Relay_On((RELAY_Name) 0);
		HAL_Delay(60U);
		Relay_Off((RELAY_Name) 0);
		HAL_Delay(60U);
	}
}

static boot0_gesture_t boot_window_relay(void)
{
	uint32_t held_ms;
	bool armed = false;

	for (uint32_t i = 0U; i < BOOT0_WINDOW_RELAYS; i++) {
		Relay_On((RELAY_Name) i);
		HAL_Delay(BOOT0_WINDOW_MS);
		Relay_Off((RELAY_Name) i);
	}

	if (boot0_is_pressed() == 0U) {
		return BOOT0_GESTURE_NONE;
	}

	/* Down at the decision point, so the board stays in the bootloader whatever
	 * happens next. Keep watching only to tell the two gestures apart. Nothing
	 * below can change that decision -- it can only add the factory reset. */
	printf("** BOOT0 held - keep holding for %u s to arm a factory reset, "
			"or let go now for upload mode **\r\n",
			(unsigned)(BOOT0_FACTORY_HOLD_MS / 1000U));

	held_ms = BOOT0_WINDOW_RELAYS * BOOT0_WINDOW_MS;
	while (boot0_is_pressed() != 0U) {
		if (!armed && (held_ms >= BOOT0_FACTORY_HOLD_MS)) {
			armed = true;
			boot0_armed_signal();
			printf("** Factory reset ARMED - release BOOT0 to run it, "
					"or reset the board to cancel **\r\n");
			/* The clicks take time of their own; count it. */
			held_ms += 6U * 60U;
			continue;
		}
		if (held_ms >= BOOT0_HOLD_LIMIT_MS) {
			printf("** BOOT0 still down after %u s - treating it as stuck, "
					"continuing in upload mode **\r\n",
					(unsigned)(BOOT0_HOLD_LIMIT_MS / 1000U));
			return BOOT0_GESTURE_UPLOAD;
		}
		HAL_Delay(BOOT0_POLL_MS);
		held_ms += BOOT0_POLL_MS;
	}

	return armed ? BOOT0_GESTURE_FACTORY_RESET : BOOT0_GESTURE_UPLOAD;
}

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* Latch the reset cause before anything can clear RCC->RSR. The cold-boot
   * test that keeps us from reading never-written ECC SRAM depends on it. */
  boot_handoff_latch_reset_cause();

  /* Enable the three configurable fault exceptions. Left at their reset default
   * they stay disabled and every MemManage / BusFault / UsageFault escalates to
   * HardFault, so IT_Fault_Report() can only ever report "HardFault" and the
   * stacked PC is the escalation point rather than the faulting instruction.
   * Enabled, each fault takes its own vector and the report names it directly.
   *
   * First statement in main(): SCB needs no clock and no init, so this covers
   * the whole boot. A fault before MX_UART4_Init() still reports over SWO/ITM. */
  SCB->SHCSR |= SCB_SHCSR_MEMFAULTENA_Msk | SCB_SHCSR_BUSFAULTENA_Msk
              | SCB_SHCSR_USGFAULTENA_Msk;

  /* Initialise the D-cache RAMs even though the D-cache stays off. They come up
   * random at power-on, tag and ECC bits included, and any invalidate-by-address
   * has to look a tag up before it can act -- landing on a random entry whose
   * ECC does not check out raises an imprecise BusFault. This pass walks the
   * cache by set and way, which writes the tags instead of looking them up, so
   * it is safe on an uninitialised cache; SCB_EnableDCache() opens with the same
   * step for the same reason. Costs tens of microseconds, once. */
  SCB_InvalidateDCache();

  /* USER CODE END 1 */

  /* MPU Configuration--------------------------------------------------------*/
  MPU_Config();

  /* Enable the CPU Cache */

  /* Enable I-Cache---------------------------------------------------------*/
  SCB_EnableICache();

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* USER CODE BEGIN SysInit */

  SystemClock_Config();

  /* Phase 1: decide. Only what the decision itself needs is brought up here, so
   * the application inherits none of our peripheral state on the jump path. */
  MX_GPIO_Init();      /* BOOT0 net, relay outputs, RS232_Enable */
  BOOT0_ConfigureAsInput();  /* undo the generated output config on PG9 */
  Enable_RX_RS232();   /* the MAX3221 stays in shutdown until this pin is high */
  MX_UART4_Init();

#if KNX_TEST_ENABLE
  KNX_Test_Run();   /* v0.1.3-testcase branch only; never returns */
#endif
#if CAN_TEST_ENABLE
  CAN_Test_Run();   /* v0.1.3-testcase branch only; never returns */
#endif
#if CAN_SOAK_TEST_ENABLE
  CAN_Test_Soak_Run();   /* v0.1.3-testcase branch only; never returns */
#endif
#if CAN_SCOPE_TEST_ENABLE
  CAN_Test_Scope_Run();   /* v0.1.3-testcase branch only; never returns */
#endif
#if CAN_ECHO_TEST_ENABLE
  CAN_Test_Echo_Run();   /* v0.1.3-testcase branch only; never returns */
#endif
#if RS485_TEST_ENABLE
  RS485_Test_Run();   /* v0.1.3-testcase branch only; never returns */
#endif
#if BRINGUP_TEST_ENABLE
  BringUp_Test_Run();   /* v0.1.3-testcase branch only; never returns */
#endif

  printf("** Checking Starting Mod ...\r\n"
		  "** (IF You want OpenPLC to stay in upload mode, please hold down the BOOT0 button for 3-5 seconds while clicking)\r\n");

  printf("** Reset cause: %s\r\n", boot_handoff_reset_cause_str());

  {
    boot0_gesture_t gesture = boot_window_relay();

    if (gesture == BOOT0_GESTURE_FACTORY_RESET) {
      /* ⚠️ BEFORE server_decide(), because that is where the owner slot is
       * scanned and reported. Clearing afterwards would make this boot's log
       * describe ownership that had just been thrown away -- the log would
       * contradict the board on the one boot where somebody is certainly
       * reading it.
       *
       * The gesture is the physical gate: ten seconds on a button nobody
       * reaches by accident, on a board somebody is standing at. */
      (void)owner_slot_factory_reset(true);
    }

    /* server_decide() only needs to know whether to stay in the bootloader.
     * Both gestures mean yes; they differ only in what happened above. */
    s_boot_mode = server_decide((gesture == BOOT0_GESTURE_NONE) ? 0U : 1U);
  }

  if (s_boot_mode == IAP_NONE) {
    server_jump_to_app();   /* hands the hardware back; never returns */
  }
  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  /* USER CODE BEGIN 2 */

  /* Phase 2: staying in the bootloader. */

  /* MX_GPIO_Init() above drove RS232_Enable low again. */
  Enable_RX_RS232();

  MX_RTC_Init();   /* iap_auth's nonce counter lives in a backup register */
  iap_auth_report_backup_domain();
  MX_CRC_Init();   /* upload checksum */
  MX_FMC_Init();   /* external SDRAM: staging area for the incoming image */

  /* IAP_ALL means the channel is unknown, so open both rather than guess. */
  if ((s_boot_mode == IAP_CDC) || (s_boot_mode == IAP_ALL)) {
    MX_USB_DEVICE_Init();
  }
  if ((s_boot_mode == IAP_ETHERNET) || (s_boot_mode == IAP_ALL)) {
    MX_LWIP_Init();
  }

  IAP_servers_start(s_boot_mode);
  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1) {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    IAP_task();
    /* MX_LWIP_Init() only ran for the ethernet modes. */
    if ((s_boot_mode == IAP_ETHERNET) || (s_boot_mode == IAP_ALL)) {
      MX_LWIP_Process();
    }
    HAL_Delay(10);
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Supply configuration update enable
  */
  HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI48|RCC_OSCILLATORTYPE_LSI
                              |RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  RCC_OscInitStruct.HSI48State = RCC_HSI48_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 2;
  RCC_OscInitStruct.PLL.PLLN = 64;
  RCC_OscInitStruct.PLL.PLLP = 2;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1VCIRANGE_3;
  RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
  RCC_OscInitStruct.PLL.PLLFRACN = 0;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_D3PCLK1|RCC_CLOCKTYPE_D1PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV2;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV2;
  RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

 /* MPU Configuration */

void MPU_Config(void)
{
  MPU_Region_InitTypeDef MPU_InitStruct = {0};

  /* Disables the MPU */
  HAL_MPU_Disable();

  /** Initializes and configures the Region and the memory to be protected
  */
  MPU_InitStruct.Enable = MPU_REGION_ENABLE;
  MPU_InitStruct.Number = MPU_REGION_NUMBER0;
  MPU_InitStruct.BaseAddress = 0x0;
  MPU_InitStruct.Size = MPU_REGION_SIZE_4GB;
  MPU_InitStruct.SubRegionDisable = 0xC7;
  MPU_InitStruct.TypeExtField = MPU_TEX_LEVEL0;
  MPU_InitStruct.AccessPermission = MPU_REGION_NO_ACCESS;
  MPU_InitStruct.DisableExec = MPU_INSTRUCTION_ACCESS_DISABLE;
  MPU_InitStruct.IsShareable = MPU_ACCESS_SHAREABLE;
  MPU_InitStruct.IsCacheable = MPU_ACCESS_NOT_CACHEABLE;
  MPU_InitStruct.IsBufferable = MPU_ACCESS_NOT_BUFFERABLE;

  HAL_MPU_ConfigRegion(&MPU_InitStruct);

  /** Initializes and configures the Region and the memory to be protected
  */
  MPU_InitStruct.Number = MPU_REGION_NUMBER1;
  MPU_InitStruct.BaseAddress = 0x30000000;
  MPU_InitStruct.Size = MPU_REGION_SIZE_128KB;
  MPU_InitStruct.SubRegionDisable = 0x0;
  MPU_InitStruct.TypeExtField = MPU_TEX_LEVEL1;
  MPU_InitStruct.AccessPermission = MPU_REGION_FULL_ACCESS;
  MPU_InitStruct.IsShareable = MPU_ACCESS_NOT_SHAREABLE;

  HAL_MPU_ConfigRegion(&MPU_InitStruct);

  /** Initializes and configures the Region and the memory to be protected
  */
  MPU_InitStruct.Number = MPU_REGION_NUMBER2;
  MPU_InitStruct.BaseAddress = 0x30020000;
  MPU_InitStruct.Size = MPU_REGION_SIZE_256B;
  MPU_InitStruct.TypeExtField = MPU_TEX_LEVEL0;
  MPU_InitStruct.IsShareable = MPU_ACCESS_SHAREABLE;
  MPU_InitStruct.IsBufferable = MPU_ACCESS_BUFFERABLE;

  HAL_MPU_ConfigRegion(&MPU_InitStruct);
  /* Enables the MPU */
  HAL_MPU_Enable(MPU_PRIVILEGED_DEFAULT);

}

/**
  * @brief  Period elapsed callback in non blocking mode
  * @note   This function is called  when TIM6 interrupt took place, inside
  * HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment
  * a global variable "uwTick" used as application time base.
  * @param  htim : TIM handle
  * @retval None
  */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  /* USER CODE BEGIN Callback 0 */

  /* USER CODE END Callback 0 */
  if (htim->Instance == TIM6)
  {
    HAL_IncTick();
  }
  /* USER CODE BEGIN Callback 1 */

  /* USER CODE END Callback 1 */
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
	/* User can add his own implementation to report the HAL error return state */
	__disable_irq();
	while (1) {
	}
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
