# Single source of truth for the IAP fixed password: iap_fixed_password.txt.
# Regenerates the three copies that actually need it in their own language
# (bootloader header, Arduino-core header, PC-tool Go const).
# To change the password: edit iap_fixed_password.txt, re-run this script,
# then commit the regenerated files in all three repos.

$Here = Split-Path -Parent $MyInvocation.MyCommand.Path
$PasswordFile = Join-Path $Here "iap_fixed_password.txt"
$ArduinoCoreDir = "C:\Users\WhoamIamwhO\AppData\Local\Arduino15\packages\OpenPLC_Alpha\hardware\stm32\0.1.3-pre\libraries\OpenPLC_IAP\src"
$IapToolCryptoDir = "E:\WorkSpace\Schaeffer-AG\IAPTranfer_Tool\iapcrypto"

if (-not (Test-Path $PasswordFile)) {
    Write-Error "$PasswordFile not found"
    exit 1
}

$Password = (Get-Content $PasswordFile -Raw).Trim()
if ([string]::IsNullOrEmpty($Password)) {
    Write-Error "$PasswordFile is empty"
    exit 1
}

function Write-CHeader($OutPath) {
    $content = @"
/* Code generated by IAPServer/generate_fixed_password.ps1 from
 * IAPServer/iap_fixed_password.txt. DO NOT EDIT -- edit that file and
 * re-run the generator instead. */

#ifndef IAP_FIXED_PASSWORD_GENERATED_H_
#define IAP_FIXED_PASSWORD_GENERATED_H_

#define IAP_FIXED_PASSWORD "$Password"

#endif /* IAP_FIXED_PASSWORD_GENERATED_H_ */
"@
    Set-Content -Path $OutPath -Value $content -Encoding ascii -NoNewline
    Write-Host "wrote $OutPath"
}

Write-CHeader (Join-Path $Here "iap_fixed_password_generated.h")
Write-CHeader (Join-Path $ArduinoCoreDir "iap_fixed_password_generated.h")

$goContent = @"
// Code generated by open_plc_cube_ide/IAPServer/generate_fixed_password.ps1
// from IAPServer/iap_fixed_password.txt. DO NOT EDIT -- edit that file and
// re-run the generator instead.
package iapcrypto

const FixedPassword = "$Password"
"@
$goPath = Join-Path $IapToolCryptoDir "fixed_password_generated.go"
Set-Content -Path $goPath -Value $goContent -Encoding ascii -NoNewline
Write-Host "wrote $goPath"
