#!/usr/bin/env bash
# Single source of truth for the IAP fixed password: iap_fixed_password.txt.
# Regenerates the three copies every build (bootloader header, Arduino-core
# header, PC-tool Go const) that actually need it in their own language.
# To change the password: edit iap_fixed_password.txt, then re-run this
# script and commit the regenerated files in all three repos.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PASSWORD_FILE="$HERE/iap_fixed_password.txt"

ARDUINO_CORE_DIR="/c/Users/WhoamIamwhO/AppData/Local/Arduino15/packages/OpenPLC_Alpha/hardware/stm32/0.1.3-pre/libraries/OpenPLC_IAP/src"
IAPTOOL_CRYPTO_DIR="/e/WorkSpace/Schaeffer-AG/IAPTranfer_Tool/iapcrypto"

if [ ! -f "$PASSWORD_FILE" ]; then
	echo "error: $PASSWORD_FILE not found" >&2
	exit 1
fi

PASSWORD="$(tr -d '\r\n' < "$PASSWORD_FILE")"
if [ -z "$PASSWORD" ]; then
	echo "error: $PASSWORD_FILE is empty" >&2
	exit 1
fi

write_c_header() {
	local out="$1"
	cat > "$out" <<EOF
/* Code generated by IAPServer/generate_fixed_password.sh from
 * IAPServer/iap_fixed_password.txt. DO NOT EDIT -- edit that file and
 * re-run the generator instead. */

#ifndef IAP_FIXED_PASSWORD_GENERATED_H_
#define IAP_FIXED_PASSWORD_GENERATED_H_

#define IAP_FIXED_PASSWORD "$PASSWORD"

#endif /* IAP_FIXED_PASSWORD_GENERATED_H_ */
EOF
	echo "wrote $out"
}

write_c_header "$HERE/iap_fixed_password_generated.h"
write_c_header "$ARDUINO_CORE_DIR/iap_fixed_password_generated.h"

cat > "$IAPTOOL_CRYPTO_DIR/fixed_password_generated.go" <<EOF
// Code generated by open_plc_cube_ide/IAPServer/generate_fixed_password.sh
// from IAPServer/iap_fixed_password.txt. DO NOT EDIT -- edit that file and
// re-run the generator instead.
package iapcrypto

const FixedPassword = "$PASSWORD"
EOF
echo "wrote $IAPTOOL_CRYPTO_DIR/fixed_password_generated.go"
