/* Code generated by IAPServer/generate_fixed_password.sh from
 * IAPServer/iap_fixed_password.txt. DO NOT EDIT -- edit that file and
 * re-run the generator instead. */

#ifndef IAP_FIXED_PASSWORD_GENERATED_H_
#define IAP_FIXED_PASSWORD_GENERATED_H_

#define IAP_FIXED_PASSWORD "IAP-FIXED-PASSWORD-TEST-ONLY-CHANGE-ME"

#endif /* IAP_FIXED_PASSWORD_GENERATED_H_ */
